import type postgres from 'postgres';

type Sql = ReturnType<typeof postgres>;

// Schema + column migrations, as one idempotent step. Run by `npm run migrate`
// (and by `npm run seed`), never automatically on import — a shared hosted
// database should not have DDL executed against it on every request.
//
// created_at stays TEXT in 'YYYY-MM-DD HH24:MI:SS' form rather than becoming
// timestamptz, so the shape of every API response is unchanged by the move off
// SQLite. Dates and times are likewise TEXT: the whole app compares them as
// strings ('2026-08-09', '18:00'), and converting them to real date/time types
// would hand back Date objects and silently break those comparisons.

// postgres.js prints every Postgres NOTICE to the console. "relation already
// exists, skipping" and "column already exists" are the expected result of
// re-running an idempotent migration, so they are dropped; anything else is
// still surfaced rather than silently swallowed.
const EXPECTED_NOTICES = new Set([
  '42P07', // duplicate_table
  '42701', // duplicate_column
  '42P06', // duplicate_schema
  '42P16', // invalid_table_definition (IF NOT EXISTS index)
]);

export function onnotice(notice: { code?: string; message?: string }): void {
  if (notice.code && EXPECTED_NOTICES.has(notice.code)) return;
  console.warn(`postgres notice: ${notice.message ?? JSON.stringify(notice)}`);
}

export async function migrate(sql: Sql): Promise<void> {
  await sql`
    CREATE TABLE IF NOT EXISTS turfs (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      name TEXT NOT NULL,
      owner_name TEXT NOT NULL,
      locality TEXT NOT NULL,
      sport TEXT NOT NULL,
      price_per_hour INTEGER NOT NULL,
      open_time TEXT NOT NULL DEFAULT '06:00',
      close_time TEXT NOT NULL DEFAULT '23:00',
      photo_emoji TEXT DEFAULT '⚽',
      photo_url TEXT,
      rating REAL DEFAULT 4.5,
      created_at TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
    )
  `;

  await sql`
    CREATE TABLE IF NOT EXISTS slot_overrides (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      turf_id INTEGER NOT NULL REFERENCES turfs(id),
      date TEXT NOT NULL,
      start_time TEXT NOT NULL,
      status TEXT NOT NULL,
      note TEXT,
      customer_name TEXT,
      payment_method TEXT,
      price INTEGER,
      created_at TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
    )
  `;

  // The database is the source of truth for slot exclusivity. Application-level
  // check-then-insert leaves a race window between the SELECT and the INSERT;
  // this index closes it by rejecting the second writer outright.
  await sql`
    CREATE UNIQUE INDEX IF NOT EXISTS idx_unique_slot
      ON slot_overrides(turf_id, date, start_time)
  `;

  await sql`
    CREATE TABLE IF NOT EXISTS pricing_rules (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      turf_id INTEGER NOT NULL REFERENCES turfs(id),
      start_time TEXT NOT NULL,
      end_time TEXT NOT NULL,
      price INTEGER NOT NULL
    )
  `;

  // Saved details only. Not authentication: no password, no session, nothing is
  // checked. Identity stays name-based, as it is everywhere else in the app.
  await sql`
    CREATE TABLE IF NOT EXISTS users (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      name TEXT NOT NULL UNIQUE,
      phone TEXT,
      role TEXT,
      created_at TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
    )
  `;

  await sql`
    CREATE TABLE IF NOT EXISTS player_requests (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      creator_name TEXT NOT NULL,
      sport TEXT NOT NULL,
      locality TEXT NOT NULL,
      date TEXT NOT NULL,
      time TEXT NOT NULL,
      players_needed INTEGER NOT NULL,
      players_joined TEXT NOT NULL DEFAULT '[]',
      pending_joiners TEXT NOT NULL DEFAULT '[]',
      status TEXT NOT NULL DEFAULT 'open',
      created_at TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
    )
  `;

  // ---- column migrations -------------------------------------------------
  // CREATE TABLE IF NOT EXISTS does nothing to a table that already exists, so
  // databases created before a column was introduced need it added separately.
  // This is the Postgres equivalent of the old PRAGMA table_info checks.
  const addColumnIfMissing = async (table: string, column: string, definition: string) => {
    const existing = await sql<{ column_name: string }[]>`
      SELECT column_name
        FROM information_schema.columns
       WHERE table_schema = 'public'
         AND table_name = ${table}
         AND column_name = ${column}
    `;
    if (existing.length === 0) {
      // Identifiers cannot be parameterised; both values are literals from the
      // call sites below, never user input.
      await sql.unsafe(`ALTER TABLE ${table} ADD COLUMN ${column} ${definition}`);
    }
  };

  await addColumnIfMissing('player_requests', 'pending_joiners', `TEXT NOT NULL DEFAULT '[]'`);
  await addColumnIfMissing('slot_overrides', 'payment_method', 'TEXT');
  await addColumnIfMissing('slot_overrides', 'price', 'INTEGER');
  await addColumnIfMissing('turfs', 'photo_url', 'TEXT');
}
