import type postgres from 'postgres';

type Sql = ReturnType<typeof postgres>;

// Schema + column migrations, as one idempotent step. Run by `npm run migrate`
// (and by `npm run seed`), never automatically on import — a shared hosted
// database should not have DDL executed against it on every request.
//
// created_at stays TEXT in 'YYYY-MM-DD HH24:MI:SS' form rather than becoming
// timestamptz, so the shape of every API response is unchanged by the move off
// SQLite. Dates and times are likewise TEXT: the whole app compares them as
// strings ('2026-08-09', '18:00'), and converting them to real date/time types
// would hand back Date objects and silently break those comparisons.

// postgres.js prints every Postgres NOTICE to the console. "relation already
// exists, skipping" and "column already exists" are the expected result of
// re-running an idempotent migration, so they are dropped; anything else is
// still surfaced rather than silently swallowed.
const EXPECTED_NOTICES = new Set([
  '42P07', // duplicate_table
  '42701', // duplicate_column
  '42P06', // duplicate_schema
  '42P16', // invalid_table_definition (IF NOT EXISTS index)
]);

export function onnotice(notice: { code?: string; message?: string }): void {
  if (notice.code && EXPECTED_NOTICES.has(notice.code)) return;
  console.warn(`postgres notice: ${notice.message ?? JSON.stringify(notice)}`);
}

export async function migrate(sql: Sql): Promise<void> {
  await sql`
    CREATE TABLE IF NOT EXISTS turfs (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      name TEXT NOT NULL,
      owner_name TEXT NOT NULL,
      locality TEXT NOT NULL,
      sport TEXT NOT NULL,
      price_per_hour INTEGER NOT NULL,
      open_time TEXT NOT NULL DEFAULT '06:00',
      close_time TEXT NOT NULL DEFAULT '23:00',
      photo_emoji TEXT DEFAULT '⚽',
      photo_url TEXT,
      rating REAL DEFAULT 4.5,
      created_at TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
    )
  `;

  await sql`
    CREATE TABLE IF NOT EXISTS slot_overrides (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      turf_id INTEGER NOT NULL REFERENCES turfs(id),
      date TEXT NOT NULL,
      start_time TEXT NOT NULL,
      status TEXT NOT NULL,
      note TEXT,
      customer_name TEXT,
      payment_method TEXT,
      price INTEGER,
      created_at TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
    )
  `;

  // The database is the source of truth for slot exclusivity. Application-level
  // check-then-insert leaves a race window between the SELECT and the INSERT;
  // this index closes it by rejecting the second writer outright.
  await sql`
    CREATE UNIQUE INDEX IF NOT EXISTS idx_unique_slot
      ON slot_overrides(turf_id, date, start_time)
  `;

  await sql`
    CREATE TABLE IF NOT EXISTS pricing_rules (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      turf_id INTEGER NOT NULL REFERENCES turfs(id),
      start_time TEXT NOT NULL,
      end_time TEXT NOT NULL,
      price INTEGER NOT NULL
    )
  `;

  // Accounts. `name` is the login identifier and `password_hash` is a bcrypt
  // digest — the raw password is never stored, logged, or returned.
  //
  // TODO: name-as-login is a real limitation. With no email or phone on the
  // account there is no way to prove someone owns it, so there is no password
  // reset: a forgotten password means a new account under a new name. Adding
  // email (and OTP) is what lifts this.
  await sql`
    CREATE TABLE IF NOT EXISTS users (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      name TEXT NOT NULL UNIQUE,
      phone TEXT,
      role TEXT NOT NULL DEFAULT 'player',
      password_hash TEXT NOT NULL DEFAULT '',
      created_at TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
    )
  `;

  await sql`
    CREATE TABLE IF NOT EXISTS player_requests (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      creator_name TEXT NOT NULL,
      sport TEXT NOT NULL,
      locality TEXT NOT NULL,
      date TEXT NOT NULL,
      time TEXT NOT NULL,
      players_needed INTEGER NOT NULL,
      players_joined TEXT NOT NULL DEFAULT '[]',
      pending_joiners TEXT NOT NULL DEFAULT '[]',
      status TEXT NOT NULL DEFAULT 'open',
      created_at TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
    )
  `;

  // ---- column migrations -------------------------------------------------
  // CREATE TABLE IF NOT EXISTS does nothing to a table that already exists, so
  // databases created before a column was introduced need it added separately.
  // This is the Postgres equivalent of the old PRAGMA table_info checks.
  const addColumnIfMissing = async (table: string, column: string, definition: string) => {
    const existing = await sql<{ column_name: string }[]>`
      SELECT column_name
        FROM information_schema.columns
       WHERE table_schema = 'public'
         AND table_name = ${table}
         AND column_name = ${column}
    `;
    if (existing.length === 0) {
      // Identifiers cannot be parameterised; both values are literals from the
      // call sites below, never user input.
      await sql.unsafe(`ALTER TABLE ${table} ADD COLUMN ${column} ${definition}`);
    }
  };

  await addColumnIfMissing('player_requests', 'pending_joiners', `TEXT NOT NULL DEFAULT '[]'`);
  await addColumnIfMissing('slot_overrides', 'payment_method', 'TEXT');
  await addColumnIfMissing('slot_overrides', 'price', 'INTEGER');
  await addColumnIfMissing('turfs', 'photo_url', 'TEXT');

  // ---- accounts migration ------------------------------------------------
  // Rows that predate passwords get an empty hash. That is not a weak password,
  // it is an unusable one: '' is not a valid bcrypt digest, and the login route
  // rejects any stored hash that is not bcrypt-shaped before it ever compares.
  // Such an account cannot be signed into and must be created again.
  await addColumnIfMissing('users', 'password_hash', `TEXT NOT NULL DEFAULT ''`);

  // `role` already existed, but as a nullable free-text field that only decided
  // which chip looked selected on the profile. It is a permission now, so it is
  // normalised to exactly 'player' | 'owner' and made NOT NULL.
  //
  // 'both' was a valid answer under the old cosmetic scheme and maps to 'owner'
  // so nobody silently loses access to a turf they run. Those rows all carry an
  // empty password_hash, so nothing can actually sign in as them regardless.
  await sql`UPDATE users SET role = 'owner'  WHERE role IN ('owner', 'both')`;
  await sql`UPDATE users SET role = 'player' WHERE role IS NULL OR role NOT IN ('player', 'owner')`;
  await sql`ALTER TABLE users ALTER COLUMN role SET DEFAULT 'player'`;
  await sql`ALTER TABLE users ALTER COLUMN role SET NOT NULL`;

  // The database refuses anything outside the two known roles, so a bug in a
  // route handler cannot write a third value that then fails open somewhere.
  const roleCheck = await sql<{ conname: string }[]>`
    SELECT conname FROM pg_constraint WHERE conname = 'users_role_check'
  `;
  if (roleCheck.length === 0) {
    await sql`ALTER TABLE users ADD CONSTRAINT users_role_check CHECK (role IN ('player', 'owner'))`;
  }

  // Names are compared case-insensitively everywhere in this app (see
  // lib/names.ts), and turf ownership is decided by matching the signed-in name
  // against turfs.owner_name. Plain UNIQUE is case-SENSITIVE in Postgres, so
  // without this index 'Ramesh' and 'ramesh' could both be registered and both
  // would satisfy the ownership check on the same turf. Login also looks the
  // account up by lower(name), which this index serves.
  await sql`
    CREATE UNIQUE INDEX IF NOT EXISTS idx_users_name_lower ON users (lower(name))
  `;
}
